feat(forms): формы готовы
majishanred/webbee_forms pull request #1
Opened 2024-08-01 19:18 UTC by majishanred

Формы формы формы

2024-08-05 13:48 UTC, myaak requested changes
Я хочу чтобы у тебя был таб менеджер, которому неважно че за табы ты хочешь рисовать.

Ты прокидываешь ему структуру своих табов, а он сам понимает че там происходит.
Ну хук наверное тоже понадобится, чтобы понимать какой таб выбран и тд.

Плохо видно на каком табе ошибка, сильно сливается, свети просто либо текст, либо фул таб, а не нижнюю полоску.

2024-08-05 13:48 UTC, myaak commented on package.json
> +    "zustand": "^4.5.4"
Не нужен тут стейт менеджер

2024-08-05 13:48 UTC, myaak commented on src/App.tsx
> +    <>
Фрагмент не нужен

2024-08-05 13:48 UTC, myaak commented on src/components/Card.tsx
> +      )}
Тут можно сделать тернарником, функцию тоже можно прокинуть по условию, т.к различие в основном в этом

2024-08-05 13:48 UTC, myaak commented on src/components/Card.tsx
> +  const [selectedTab, setSelectedTab] = useState<string>('contacts');
М.. Почему у тебя менеджментом табов занимается карточка.

Хочется получить универсальный компонент таба, который примет какую-то структуру внутрь

2024-08-05 13:48 UTC, myaak commented on src/components/Card.tsx
> +          <ProjectsTab tab={selectedTab} setTab={setSelectedTab} />
Зачем стейт передавать каждому табу, получается у тебя стейт этой штуки меняет таб внутри. Не думаю, что красиво

2024-08-05 13:48 UTC, myaak commented on src/components/Card.tsx
> +        </Button>
button в муи по дефолту апперкейс вроде.

Мы не пишем обычно прям в ловеркейсе все. пишем обычно `Редактировать`, а там как нужно приводим руками. Все маленькими или все большими не пишем

2024-08-05 13:48 UTC, myaak commented on src/components/contactsForm/components/EmailField.tsx
> +import { Controller } from 'react-hook-form';
Что, зачем тебе кучу компонентов похожих друг на друга. Тебе достаточно инфы `name, control`. Ты можешь сделать универсальный компонент, в который ты пару пропов кинешь, не нужно делать для каждого инпута отдельный компонент

2024-08-05 13:48 UTC, myaak commented on src/components/contactsForm/components/PhoneField.tsx
> +      mask: '+{7}(000)000-00-00',
По хорошему маску валидируем через zod + используем maskedTextField

2024-08-05 13:48 UTC, myaak commented on src/components/projectForm/ProjectForm.tsx
> +    <FormProvider {...methods}>
Как раз отсюда контекст можешь взять для "универсального" текстфилда

2024-08-05 13:48 UTC, myaak commented on src/components/projectForm/components/EndingDateField.tsx
> +  const endingDate = useInfoStore((state) => state.projects[projectId]!.endDate);
`!` используем только в крайних случаях. Оно всегда стреляет в ногу, как правило. Типизируй нормально

2024-08-05 13:48 UTC, myaak commented on src/components/projectForm/components/RoleField.tsx
> +const roles = ['Разработчик', 'Тестер', 'Девопс', 'ПМ', 'Шлёпа'];
Шлепа топовая роль, но почему оно тут лежит. Либо в самом верху, либо в отдельном файле. Обычно до низа никто не листает

2024-08-05 13:48 UTC, myaak commented on src/components/projectForm/components/SkillsField.tsx
> +      )}
Этот рендер можно и в отдельный компонент вынести

2024-08-05 13:48 UTC, myaak commented on src/components/projectForm/components/SkillsField.tsx
> +const sklls = ['vue', 'react', 'nodejs', 'next', 'angular', 'svelte'];
Это все можно вынети в один файл, и skills и roles, имхо

2024-08-05 13:48 UTC, myaak commented on src/hooks/useProjectForm.ts
> +export const useProjectForm = useFormContext<ProjectInfo>;
Зачем ссылку тут передаешь, обычно передают что в контексте лежит. Файл очень странный

2024-08-05 13:48 UTC, myaak commented on src/schemas/ContactsSchema.ts
> +  luboiDvij: z.boolean().refine((check) => check, 'Ты обязан быть за любой движ'),
Конечно это рофл, но переменная называется ааааа

2024-08-05 13:48 UTC, myaak commented on src/schemas/ProjectSchema.ts
> +export type ProjectFormFields = z.infer<typeof projectSchema>;
Не сильно знаю zod, но чаще всего типы которые генерируются валидаторами обычно фигня. Пишем типы сами, а потом говорит `schema: SchemaOf<CustomType>`

2024-08-05 13:48 UTC, myaak commented on src/stores/InfoStore.ts
> +*/
Да, нужно выпилить стор 😄

2024-08-05 13:48 UTC, myaak commented on src/utils/formatDate.ts
> +  if (formatedDate === 'Invalid Date') return null;
Ну invalid date наверное будет, если это не объект даты или чето еще.

ты можешь выкинуть `null` сразу, у тебя `undefined` никогда не сконвертится  в дату

2024-08-05 13:48 UTC, myaak commented on src/types/Contacts.ts
> +  hasError: unknown;
Как так-то, почему неизвестный, ты же его написал

2024-08-05 13:48 UTC, myaak commented on src/stores/InfoStore.ts
> +    [id: number]: Project | null;
У тебя у объекта ключ всегда строка

2024-08-05 13:48 UTC, myaak commented on src/main.tsx
> +import React from 'react';
Тут можно не тянуть весь реакт, а просто импортировать `StrictMode`

2024-08-05 13:48 UTC, myaak commented on src/components/projectForm/components/RoleField.tsx
> +            onChange={(event) => changeProjectField(projectId, 'role', event.target.value)}
Почему этим вообще стор занимается, а как же форма

2024-08-05 13:48 UTC, myaak commented on src/components/projectForm/components/NameField.tsx
> +            error={Boolean(error)}
`!!error`

2024-08-05 13:48 UTC, myaak commented on package.json
> +    "dayjs": "^1.11.12",
`date-fns` обычно на фронте используем у нас, но `dayjs` наверное тоже клевый

2024-08-05 14:09 UTC, majishanred commented on src/utils/formatDate.ts
> +  if (formatedDate === 'Invalid Date') return null;
Там прикол Dayjs, invalid date это вообще че угодно, кроме валидной даты, которую ты в формат прокидываешь, я чекал это

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/Card.tsx
3 вещи описаны в одном файле, надо бить, иначе это дичь

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/Card.tsx
> +        </Button>
Очень не круто таким образом в принципе описывать, у тебя одинаковый компонент, он отличия лишь в функции и имени, нет смысла выносить в отдельную

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/Card.tsx
> +};
Используй табы из mui

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/Card.tsx
> +
выноси в отдельный файл

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/contactsForm/ContactsForm.tsx
> +            <MiddleNameField disabled={isValidated} />
Не надо так дробить, слишком сильно это делишь, пили базовые прям
вот тебе нужно текстовый инпут, все выносим именно текстовый, а не определенный

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/contactsForm/components/PhoneField.tsx
> +      mask: '+{7}(000)000-00-00',
Полностью согласен

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/projectForm/ProjectForm.tsx
> +  const methods = useForm<ProjectInfo>();
а что зод не используешь почему?
И смотри, у тебя это все одна большая форма, одна и та же, и она должна быть единой сущностью
то есть по сути именно useForm вызов у тебя должен быть всего один

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/projectForm/ProjectForm.tsx
Опять же в одном файле только один компонент, все остальное в новый файл

2024-08-12 12:45 UTC, IvanKoigerov commented on src/components/projectForm/components/BeginDateField.tsx
> +  const changeDate = useCallback((e: Dayjs | null) => {
не сокращай такие вещи, что за e
лучше всего писать event
А тут и тип ещё Dayjs, значит это не просто event

2024-08-13 14:48 UTC, majishanred commented on src/components/contactsForm/components/EmailField.tsx
> +import { Controller } from 'react-hook-form';
Вот тут вопрос, делать в принципе супер универсальный таб, который получает кучу пропов и внутри решает что делать, или универсальный таб чисто для обычных инпутов, не дейтпикеров и тд.

2024-08-13 15:06 UTC, majishanred commented on src/schemas/ContactsSchema.ts
> +  luboiDvij: z.boolean().refine((check) => check, 'Ты обязан быть за любой движ'),
А как мне ее назвать?)

2024-08-14 07:33 UTC, IvanKoigerov commented on package.json
> +    "zustand": "^4.5.4"
@majishanred не удалил

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/Card/Card.tsx
> +            hasErrors={!isObjectEmpty(methods.formState.errors)}
хорошо

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/Card/Card.tsx
> +            }
такие большие темы лучше всего выносить в отдельную функцию

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/Card/Card.tsx
> +    ${({ hasErrors, theme }) => hasErrors && 'background-color: ' + theme.palette.error.main};
background-color: ${({ hasErrors, theme }) => hasErrors ? theme.palette.error.main : undefined};

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/Card/IsFormActive.context.tsx
> +  const func = useContext(SetIsFormActiveContext);
что такое func, не очень понятное имя)

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/Card/IsFormActive.context.tsx
> +  return ctx;
Как и это

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/Card/IsFormActive.context.tsx
> +};
Да и будто бы лучше сделать какую-то обертку, которая проверяет есть ли контент у контекста, иначе ошибка

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/Card/IsFormActive.context.tsx
ещё если юзаешь !isFormActive, то лучше сделать isDisabled тогда уж

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ContactsForm/ContactsForm.tsx
> +          <TextFieldWrapper name="contacts.middleName" label={'Отчество'} disabled={!isFormActive} />
не очень круто писать так label={''} а не label=''

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ContactsForm/LuboiDvijField.tsx
мы делаем именно базовые компоненты, которые мы можем использовать во всем приложении, а тут у нас чекбокс с заполненным именем 
Также у тебя тут name заполнен, в такой ситуации ты только в одном место его можешь использовать и только для этой задачи

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ContactsForm/PhoneNumberField.tsx
тут тоже самое что и с чекбоксом, ни лейбл ни нейм не должны быть таким образом предзаполнены

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ProjectForm/DateComponent.tsx
Вот это хорошо сделаный компонент, только желательно чтобы он в себя принимал больше пропов и больше мог модернизироваться со стороны

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ProjectForm/DateComponent.tsx
> +}) => {
выносим в тип всегда, даже если одно поле

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ProjectForm/ProjectForm.tsx
> +  const isValidated = useMemo(() => !isFormActive || projectData.isValidated, [projectData, isFormActive]);
не круто что в одну строчку написан

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ProjectForm/ProjectForm.tsx
> +              }}
просто onClick={deleteProject}

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ProjectForm/ProjectForm.tsx
> +              }}
Вообще всегда старайся именно так их описывать, меньше текста кода, отступов в такой ситуации, да и чуть по читабельнее

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ProjectForm/ProjectForm.tsx
> +        <RolesComponent name={`projects[${projectIndex}].role`} disabled={isValidated} />
одно у тебя селект и другое автокомплид, нужно было сделать из именно базовую удобную реализацию, а в этом файле уже модифицировать базовый элемент

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/ProjectForm/SkillsComponent.tsx
> +            }}
очень дрочно, используй тут autocomplite, а не селект

2024-08-14 07:33 UTC, IvanKoigerov commented on src/components/TextFieldWrapper/FormFieldWrapper.type.ts
> +};
заекстендись от типа TextField и по большем радуйся жизни, ну а также чисто из интереса можешь чекать что происходит на реальном проекте) 
Но это делай в крайнем случае

2024-08-14 07:33 UTC, IvanKoigerov commented on src/main.tsx
> +import React from 'react';
@majishanred

2024-08-14 07:33 UTC, IvanKoigerov commented on src/main.tsx
> +);
Вообще не правильно тут хоть что-то делать кроме 

<React.StrictMode>и <App /> тут ничего не должно быть лишнего, это вход в твой проект, и тут мы не должны писать ничего лишнего

2024-08-14 07:33 UTC, IvanKoigerov commented on src/schemas/FormSchema.ts
> +    middleName: z.optional(z.string().min(1, 'Не бывает такого короткого отчества')),
Почему не required?
А ещё я писал про trim, юзай его

2024-08-14 07:33 UTC, IvanKoigerov commented on src/schemas/FormSchema.ts
> +      });
будто бы не очень круто его использовать прям в required, можно вынести саму маску

2024-08-14 07:33 UTC, IvanKoigerov commented on src/schemas/FormSchema.ts
> +      })
тут ошибки не будет как я помню

2024-08-14 07:33 UTC, IvanKoigerov commented on src/schemas/ProjectSchema.ts
> +    role: z.string().min(1, 'Обязательное поле'),
Почему не required?

2024-08-14 07:33 UTC, IvanKoigerov commented on src/schemas/ProjectSchema.ts
> +      .length(10, 'Некоректная дата'),
Почему не date тип? так было бы проще сравнивать, а ещё надо оба варианта проверять позже или раньше он, и это можно сделать сильно проще

2024-08-14 13:03 UTC, majishanred commented on src/schemas/ProjectSchema.ts
> +    role: z.string().min(1, 'Обязательное поле'),
Mui начинает ругаться, если в компоненты залетают null или undefined, а zod ест пустую строку и не выдает ошибок.

2024-08-14 13:03 UTC, majishanred commented on src/schemas/FormSchema.ts
> +      })
Вроде в таске чекбокс помечен как required

2024-08-14 13:04 UTC, majishanred commented on src/schemas/FormSchema.ts
> +    middleName: z.optional(z.string().min(1, 'Не бывает такого короткого отчества')),
трим в onChange в текстфилдах есть, зачем он в валидации?

2024-08-20 14:08 UTC, IvanKoigerov commented on src/commons/AutocompleteWrapper/AutocompleteWrapper.tsx
> +      )}
Странно как у тебя работает если ты control не юзаешь

2024-08-20 14:08 UTC, IvanKoigerov commented on src/commons/AutocompleteWrapper/AutocompleteWrapper.types.ts
> +  valueOptions: string[] | { label: string }[];
{ label: string, value: какой-то тип } тогда уж

2024-08-20 14:08 UTC, IvanKoigerov commented on src/commons/CheckboxWrapper/CheckboxWrapper.tsx
> +      )}
И тут контрола нет, что странно

2024-08-20 14:08 UTC, IvanKoigerov commented on src/commons/DateComponent/DateComponent.tsx
> +              if (!value) {
И тут контрола нет, что странно

2024-08-20 14:08 UTC, IvanKoigerov commented on src/commons/DateComponent/DateComponent.types.ts
> +export type DateComponentProps = {
Почему не унаследуешься от пропов DatePicker + свои

2024-08-20 14:08 UTC, IvanKoigerov commented on src/commons/SelectWrapper/SelectWrapper.types.ts
> +  ListboxComponent?: 'ul' | 'ol' | 'div';
А зачем это, не особо вижу смысла

2024-08-20 14:08 UTC, IvanKoigerov commented on src/commons/TextFieldWrapper/TextFieldWrapper.tsx
> +const TextFieldWrapper = ({
TextFieldWrapper Это же не враппер, враппер это просто родитель который позиционирует элимент, враппер это только про стили, а не про форму

2024-08-20 14:08 UTC, IvanKoigerov commented on src/components/ProjectForm/ProjectForm.tsx
> +    const result = await trigger(`projects[${projectIndex}]` as `projects.${number}`);
as const

2024-08-20 14:08 UTC, IvanKoigerov commented on src/schemas/FormSchema.ts
> +    middleName: z.optional(z.string().min(1, 'Не бывает такого короткого отчества')),
легче тут описать, он все сам сделает и опишеь и ты париться не будешь, плюс руками там не надо это писать, а так

2024-08-20 14:08 UTC, IvanKoigerov commented on src/schemas/FormSchema.ts
> +    middleName: z.optional(z.string().min(1, 'Не бывает такого короткого отчества')),
Есть более хороший вариант реквайред описать, поищи

2024-08-20 14:08 UTC, IvanKoigerov commented on src/schemas/ProjectSchema.ts
> +    role: z.string().min(1, 'Обязательное поле'),
он их игнорит при том моменте когда ты сабмит кликаешь? ну если это кал, то это калл

2024-08-21 14:11 UTC, majishanred commented on src/components/ProjectForm/ProjectForm.tsx
> +    const result = await trigger(`projects[${projectIndex}]` as `projects.${number}`);
![image](https://github.com/user-attachments/assets/ee45b5fc-2490-429f-ac53-34669c3d46a2)
Неа

2024-08-21 18:22 UTC, majishanred commented on src/components/ProjectForm/ProjectForm.tsx
> +    const result = await trigger(`projects[${projectIndex}]` as `projects.${number}`);
Там надо было просто через 'projects.${number}'

2024-08-23 03:57 UTC, merged